#adding base os image for the container
FROM ubuntu

#updating the libraries and installing prebuild request i.e nginx
RUN apt-get update
RUN apt-get install upgrade -y
RUN apt-get install nginx

#coping the file
COPY ./code ./code