#adding base os image for the container
FROM ubuntu

#updating the libraries and installing prebuild request i.e nginx
RUN apt-get update |apt upgrade -y
RUN apt install nginx -y 

WORKDIR /web_app
#coping the file
COPY /code /var/www/html


#coping the file
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
